---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matterbuild
namePrefix: matterbuild-

bases:
- ../../base
- ../../config

resources:
- ingress.yaml

images:
- name: mattermost/matterbuild
  newName: mattermost/matterbuild
  digest: sha256:ea6b92423a5d8464255f42cfd28157d888d501f74f2c3ae28922817404f6109f
